include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
  exclude:
    - lib/src/resources/intl/messages*.dart

linter:
  rules:
    public_member_api_docs: false
    directives_ordering: false