name: pattle
description: An easy to use Matrix app.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injector: ^1.0.8

  matrix_sdk: ^0.29.0
  matrix_sdk_sqflite: ^0.20.0

  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  provider: ^4.0.1
  equatable: ^1.0.1

  intl: ^0.16.1

  cached_network_image: ^2.0.0-rc.1
  flutter_cache_manager: ^1.1.3

  sqflite: ^1.1.6

  async: ^2.3.0

  # TODO: Use official package when PR is merged
  sentry:
    git: https://git.pattle.im/forks/sentry.git

  device_info: ^0.4.1+1
  package_info: ^0.4.0+5

  # TODO (maybe): Use official package when PR is merged
  flutter_html:
    git: https://git.pattle.im/forks/flutter_html.git

  flutter_dotenv: ^2.0.1

  respect_24_hour: ^0.0.2

  transparent_image: ^1.0.0

  photo_view: ^0.4.2

  url_launcher: ^5.1.0

  image_picker: ^0.6.1+3

  image: ^2.1.4

  mime: ^0.9.6+3

  dynamic_theme: ^1.0.1

  shared_preferences: ^0.5.3+4

  mdi: ^0.2.1

  shimmer: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.8

  flutter_local_notifications: ^0.8.4

dependency_overrides:
  matrix_sdk:
    git:
      url: https://git.pattle.im/pattle/library/matrix-dart-sdk.git
      ref: f506fb387e6fcacbf90fca6551f7f8865cb6812b
  matrix_sdk_sqflite:
    git:
      url: https://git.pattle.im/pattle/library/matrix-dart-sdk-sqflite.git
      ref: 7dbb3cba4ae124c3557ccb80986dc2e95c8ae276

dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1

  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.9

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/launcher.png"
  image_path_ios: "assets/icons/launcher-full.png"
  adaptive_icon_background: "#aa4139"
  adaptive_icon_foreground: "assets/icons/launcher-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - .env
